language: scala

env:
  global:

script: sbt test:compile "hot -psource=scalap -w1 -f1" "; project compilation ; +test" "micro/jmh:run -w1 -f1"

jdk:
  - oraclejdk8

notifications:
  email: jzaugg@gmail.com
